package bytecode.classFileInterpretation.parsing.constantConcreteInfoParsers;

import bytecode.classFileInterpretation.parsing.Constant_info_parser;

public class Constant_Invoke_Dynamic_info_parser extends Constant_info_parser {
}
